### ISSUE TITLE
Toggle Totalmix FX in Windows

### ISSUE THREAD

**Issue by zerodividesbyyou** [shells-dw/streamdeck-totalmix#5]
Hello there! 
I didn't see this option in the universal OSC toggles, so I'm wondering if it's possible for you to include a button on the plugin that toggles the visibility of totalmix, just like you can choose that option for one of the hardware buttons on the interface or ARC-USB. I'd appreciate that feature a lot! Thanks for making this plugin, it's super useful!

**Comment by shells-dw** [comment]
Hey there!
I've been off this project for over a year now, I've completely moved to UA interfaces and MacOS for that kind of work last year, so this project was kind of dead for me, to be honest - however I still got my Fireface UC laying around and used that for a project recently so I figured I'd give this a look again and maybe help some of you guys out that still use them.

RME doesn't provide the option to toggle it like you can with the ARC or hardware buttons sadly, otherwise I'd have included it in the first place, always was a thing that bugged me too (but probably not enough to actually look for other solutions).

I've implemented a solution that is based on Windows functions to accomplish the same. In debugging it works fine, however I'll include some other the other requests here as well before I provide a new version. Hang in there, it shouldn't take long to get an updated version out :)

**Comment by zerodividesbyyou** [comment]
WOW! Thank you for getting back to us! Quick question for you, is there a reason in particular that you prefer the UA ecosystem? I can imagine it's the hardware based plugins and their own SoCs but I cannot live without Totalmix. Is there similar functionality available within their driver or ecosystem without using something like Soundflower on MacOS or Voicemeeter? I've used Voicemeeter before but without a super accurate driver on Windows (since you're using another ASIO driver in the middle) the timing errors can cause pops and clicks with ASIO applications. I wish Windows audio subsystem could be like MacOS, and I've actually turned my PC into a dual boot hackintosh but am dealing with some strange USB problems. If Logic or Ableton Live 10 will even run well at all... 

Anyway I very much appreciate your answers and working on this just for us! You're great!

**Comment by shells-dw** [comment]
Well, I probably could write a whole novel about the reasons and differences but I'm trying to keep it short (and most certainly fail with that) - all is based on my personal experiences and how my brain works, so your views and mileage my vary ;-)

When I wanted to upgrade my own interface last year (needed more XLR ins and general outs mainly) I looked what was available and reasonable and worked nice with MacOS, as I also switched back to MacOS and Logic as main DAW mainly for compatibility reasons with other people I started working with, which ended in basically 4 interfaces that were available here and somewhat in the same price range, the Apollo x8, the RME Fireface UFX+, the Apogee Ensamble and the Prism Titan. Now, RME went out because of the single fact, that they have their inputs on the front. I get it is useful for some people, but it sure ain't for me. I don't have a rack with all sorts of hardware in it and a patch bay to then plug 4 XLRs in the front of the interface and have the cables hang down infront of other hardware or laying on my desk (or buy additional hardware and spend another couple grand to work around that). So that was not gonna happen. Prism I didn't know well, I can't really remember coming across one and Apogee I don't really trust (that's just me). Other interfaces were not ticking my hardware requirements or were simply not available or too expensive. Also I got a good deal on the Apollo x8 plus got a Satellite (DSP Box) for free, so I went for UA. And yes, the quality of their plugins and the DSPs to take load off Logic (which struggles quite a bit on with a lot of plugins in the chain, way earlier than other DAWs I used) played a role too, most of that stuff is just out of this world good and with their Unison Preamp emulations that interface can sound a lot like gear I can't afford (and it wouldn't be reasonable to buy it anyways), so for me it's just the best interface around if you have the money for the hardware and the additional money for all their plugins (well you don't need all, but you'll sure want them, hehe). I also like that you can couple multiple (I think up to 4) of their interfaces together and control it (basically) as one. That's just amazing, I just like it. Need more ins? Just get/borrow another apollo, hook it up - tada more faders appear and just work. Loving it. So much about free advertising I guess.
They got their own DAW too as you've probably heard, called LUNA. Have played around with it, nice, very responsive and quite fast, but as said, I work mainly with Logic projects so I couldn't really be bothered to try it out yet. Maybe I'll try mixing on it one day, but the general point being it integrates very nicely with their interfaces, obviously.
I have no clue if it works on Windows though, I've never had a machine with Thunderbolt ports (very uncommon in Windows despite on these high end business laptops which then are totally unreasonable to use for tracking or music making) and the cards are insanely expensive.
There's a learning curve to the Console app and how you use it, especially if you come from RME I think. I struggled a bit in the beginning anyways.

Despite that I started getting to know UA interfaces I came across over time and I kinda dug them and their sound really, it's not quite as transparent and (I'd call it) crystal clear as the RME interfaces I used before (the interface sound without any fancy Unison Emulations on it, comparing those would just be unfair), but I really like the sound and the very very slight coloring of their preamps, whatever you track just feels a tiny tiny bit more alive (that being said, I do mostly stuff that goes with distorted guitars or at least it's more in the general Rock/heavy range, if I'd do orchestral music or something alike I might prefer an RME interface there, but that might be just in my head and most certainly the mic choice would make a whole lot more of a difference than the interface itself. I more or less exclusively do tracking and mixing with it - so it's only signals going in the DAW or coming out (and maybe going in again after running through a hardware chain) - and not that RME couldn't do that, but on UA's Console application (that's some sort of equivalent to TotalMix) I personally think, it's not so nice and fancy to route traffic inside the interface like in TotalMix, you see that they mainly had the use as a recoding interface clearly in mind when making the Console application. When I need to route audio "live" without DAW is the moment when I pull out an RME Interface and TotalMix - it's not that you couldn't do that on an Apollo, but basically everyone who has some understanding of how faders and signal flows work can use TotalMix and it's visible, reasonable and easy, quite in contrary, for me personal, to UA's Console application (again, for that limited usecase). TLDR: Apollos are great for in and out, not so great for routing audio around without involving a DAW.

I tried Voicemeeter when I had way more time for gaming and that kind of stuff a while back and it was no fun. That thing did stuff all over the place but seldomly just worked, hated it. Not sure if you could use a word clock to get rid of the timing issues with it, but I somewhat doubt it haha.

Logic won't run on Hackintosh AFAIK, I tried that many many years ago (when there was no budget for a Mac) and failed miserably after days of fiddeling around. I just couldn't get the audio inputs to work at all, not even talking reliably here. Other than that the machine was running more or less meh-ish but working, just Logic wasn't able to use any audio input. All sorts of strange things happened I can't really remember clearly now.

So, short answer regarding similar functionality: You can do it with Console, however if you really need routing audio around "inside" the interface, you're probably better off with RME. If you do tracking and mixing, I would say it makes not much of a difference once you learned how Console works from a software point of view.
Regarding performance I couldn't tell a difference, I used both RME and UA interfaces with internal effects... couldn't say I noticed any difference in performance or delays, but that being said they all have compensations for that anyways so you probably wouldn't notice unless you're overdoing it.
Generally speaking... there's probably a reason Apollos are more or less the industry standard and you see them everywhere and that's not (just) good marketing.

**Comment by shells-dw** [comment]
Alright, I've published a new release that should be able to hide and restore the TotalMix window (OSC Trigger Global Function -> "Show/Hide TotalMix UI"). Before I figured out how I get that in the new Elgato store now, you can download the new version from the [Release](https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release) folder - just install it normally, that should overwrite the one from the store.
I'd appreciate if you'd let me know if that works for you.
Cheers

**Comment by zerodividesbyyou** [comment]
Excellent, thank you very much for your detailed response. Yeah I appreciate the info about the system, and yeah checks out. From what I've seen most of those interfaces don't work on Windows, and I prefer Totalmix and the performance of these interfaces over the others. UA effects are nice but I'm not in that ecosystem and honestly don't really plan to be. I'll test out the plugin, thank you!

And actually, you can easily run Logic on Hackintoshes. Mac hacks have come a LONG way and honestly with OpenCore it's quite ez to have a modern and very powerful hackintosh running perfectly. Even on Big Sur.

**Comment by Elf86** [comment]
Hi there!

First of all, thank you so much for making this!
I've just downloaded your plugin and it works fine on my UC except one thing. 
I made a folder on stream deck with all the TotalMix controls and toggle UI works fine, but when go back up to main page of my stream deck and then go to Total Mix folder again, toggle UI doesn't work anymore until i open TotalMix manually with my mouse. Other shortcuts still work. 

I'm using OSC for control, W10, latest updates and UC drivers installed.

Cheers!

**Comment by shells-dw** [comment]
Hi Elf86,
sorry it took a while to find time to work this out. My current job involves being away from home for extended periods of time and I'm not really using RME interfaces any longer - also I've kind of overseen this issue down here.

Anyway... I've published a new version, you can find it in this repo under the [Release](https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release) folder and see if that works better.
The problem there was, that once you go back to the top folder of Stream Deck, it automatically reloads all plugin settings which deleted my cached values for the hidden window (Windows is not too helpful when it comes to addressing hidden windows that do not belong to the same process from which you're trying to mess with them) thus it couldn't address the correct Window anymore after reload. Did never notice that when I programmed it... So thanks for pointing it out.
Hopefully I found a workaround for that now, at least it works on my machine.
Let me know, if it doesn't.
Cheers

**Comment by Elf86** [comment]
﻿Hey, thank you so much, i understand your situation and appreciate your effort to help.
I’ll download it in a few hours and will write you back with feedback.

Thanks again!

Nemanja

Sent from my iPhone

On 28. 4. 2022., at 14:58, shells-dw ***@***.***> wrote:

﻿

Hi Elf86,
sorry it took a while to find time to work this out. My current job involves being away from home for extended periods of time and I'm not really using RME interfaces any longer - also I've kind of overseen this issue down here.

Anyway... I've published a new version, you can find it in this repo under the Release<https://github.com/shells-dw/streamdeck-totalmix/tree/master/Release> folder and see if that works better.
The problem there was, that once you go back to the top folder of Stream Deck, it automatically reloads all plugin settings which deleted my cached values for the hidden window (Windows is not too helpful when it comes to addressing hidden windows that do not belong to the same process from which you're trying to mess with them) thus it couldn't address the correct Window anymore after reload. Did never notice that when I programmed it... So thanks for pointing it out.
Hopefully I found a workaround for that now, at least it works on my machine.
Let me know, if it doesn't.
Cheers

**Comment by Elf86** [comment]
Sorry, just thought i could notify you, this started to happen when i try to open TotalMix:
![Capture1](https://user-images.githubusercontent.com/99021130/165942114-ce6fbae8-1de3-4642-814a-726f0ac0c7f5.JPG)
.

I know you don't have time and i already appreciate what you did, but maybe someone else will see this and get an idea what might be that problem.

Cheers! :)

**Comment by shells-dw** [comment]
yeah, I had this too during my testing, but I couldn't really reproduce it (and still can't), it's working fine for me, no matter what I do, I restarted my machine probably 15 times to try and have that happen again, but couldn't.
It seems TotalMix has some subprocesses, one of which seems to have this kind of window here - the way I try to restore the TotalMix window without knowing its handle (and without being part of the process I try to unhide again) is, basically, to restore the main subprocess of the TotalMix process ID. It appears that in some cases the handle of this socket notification sink window thingy is hit before the TotalMix window itself.
As said, Windows is not really helpful with this kind of stuff and the fact that TotalMix has to "hide" itself instead of just being minimized complicates things additionally.
I can understand it's annoying, but try to close TotalMix and reopen it (they put it under %windir%\system32\TotalMixFX.exe) whenever this happens, otherwise I don't know how to address that unless I can somehow reliably reproduce it.

Yep, just updated, but changed nothing on this front, swapped only the images of the plugin ;)

**Comment by Elf86** [comment]
I understand. I'm just gonna kill it/reopen it if it starts acting weird. 
You've already done a lot, so thanks again!

Cheers!
